"""update_database

Revision ID: 389faa54692e
Revises: 
Create Date: 2018-09-07 21:36:54.026476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '389faa54692e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seller_login_model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('seller_phone', sa.String(length=11), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seller_phone')
    )
    op.create_table('seller_shop',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pub_id', sa.String(length=16), nullable=True),
    sa.Column('shop_name', sa.String(length=32), nullable=False),
    sa.Column('shop_img', sa.String(length=128), nullable=True),
    sa.Column('shop_rating', sa.Float(), nullable=True),
    sa.Column('brand', sa.Boolean(), nullable=True),
    sa.Column('on_time', sa.Boolean(), nullable=True),
    sa.Column('fengniao', sa.Boolean(), nullable=True),
    sa.Column('bao', sa.Boolean(), nullable=True),
    sa.Column('piao', sa.Boolean(), nullable=True),
    sa.Column('zhun', sa.Boolean(), nullable=True),
    sa.Column('start_send', sa.Float(), nullable=True),
    sa.Column('send_cost', sa.Float(), nullable=True),
    sa.Column('notice', sa.String(length=210), nullable=True),
    sa.Column('discount', sa.String(length=210), nullable=True),
    sa.Column('seller_pid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['seller_pid'], ['seller_login_model.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_name')
    )
    op.create_index(op.f('ix_seller_shop_pub_id'), 'seller_shop', ['pub_id'], unique=True)
    op.create_table('menu_category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pub_id', sa.String(length=16), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('type_accumulation', sa.String(length=16), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('shop_id', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['seller_shop.pub_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('menu_food',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('goods_id', sa.String(length=8), nullable=True),
    sa.Column('goods_name', sa.String(length=64), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('goods_price', sa.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('month_sales', sa.Integer(), nullable=True),
    sa.Column('rating_count', sa.Integer(), nullable=True),
    sa.Column('tips', sa.String(length=128), nullable=True),
    sa.Column('goods_img', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['menu_category.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['seller_shop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menu_food')
    op.drop_table('menu_category')
    op.drop_index(op.f('ix_seller_shop_pub_id'), table_name='seller_shop')
    op.drop_table('seller_shop')
    op.drop_table('seller_login_model')
    # ### end Alembic commands ###
